CREATE TABLE [dbo].[MeteringPointPeriod] (
  [Id] BIGINT IDENTITY(1,1) PRIMARY KEY,
  [MeteringPointId] BIGINT NOT NULL,
  [ValidFrom] DATETIME,
  [ValidTo] DATETIME,
  [RetiredById] BIGINT,
  [RetiredAt] DATETIME,
  [OrchestrationStepId] BIGINT,
  [DH2BusTransDosiId] BIGINT,
  [Type] VARCHAR(50),
  [SubType] VARCHAR(50),
  [Resolution] VARCHAR(50),
  [GridAreaCode] VARCHAR(50),
  [OwnerGLN] VARCHAR(50),
  [AssetType] VARCHAR(50),
  [DisconnectType] VARCHAR(50),
  [MeasureUnit] VARCHAR(50),
  [FuelType] VARCHAR(50),
  [FromGridAreaCode] VARCHAR(50),
  [ToGridAreaCode] VARCHAR(50),
  [MeterNumber] VARCHAR(50),
  [MeterReadingOccurrence] VARCHAR(50),
  [Capacity] DECIMAL(10,2),
  [ConnectionType] VARCHAR(50),
    --[NetSettlementGroup] VARCHAR(50),
  [SettlementGroup] VARCHAR(50), -- DH3 name
  [ParentMeteringPoint] BIGINT,
  [PhysicalStatus] VARCHAR(50),
  [PowerLimitA] INT,
  [PowerPlantGLSRN] VARCHAR(50),
  [ProductCode] VARCHAR(50),
  [ProductionObligation] BIT,
  [ScheduleMeterReading] BIT,
  [InstallationAddressId] BIGINT NOT NULL,
  CONSTRAINT [FK_MeteringPointPeriod_MeteringPointId] FOREIGN KEY ([MeteringPointId]) REFERENCES [dbo].[MeteringPoint]([Id]),
  CONSTRAINT [FK_MeteringPointPeriod_InstallationAddressId] FOREIGN KEY ([InstallationAddressId]) REFERENCES [dbo].[InstallationAddress]([Id])
);
